### ISSUE TITLE
Crash when syncing data to Firefly

### ISSUE THREAD

**Issue by Crumar** [robvankeilegom/firefly-III-paypal-importer#9] opened 2022-07-22 16:54 UTC
![image](https://user-images.githubusercontent.com/2611791/180487117-952ad160-755a-4677-8872-27e706281849.png)

Just gave it a try, importer web reports 828 transactions.
I checked Firefly, and the list of transactions had 85.

Where can I find additional logs?

**Comment by greener-hayden** [comment] 2022-08-02 13:48
Experiencing the exact same error of 586 & the no query results. But i'm also not receiving any transactions imported in firefly. I think its something associated with firefly since when i change the domain in the cfg its it gives me
Pushing data to Firefly
Done

**Comment by robvankeilegom** [comment] 2022-08-11 09:56
Hi guys, thanks for your patience! 

> Where can I find additional logs?

Logging is stored under `storage/logs`. 

The transactions amount on the web overview used to report all transactions. This included conversions from one currency to another. In `0.2.5` I changed this to only display transactions that should be pushed to Firefly.

I also added an extra sentence telling the amount of transactions that are actually pushed. So it should display something like ` Instance contains x transactions. y of which are pushed to your Firefly instance.` now.

There also used to be a an issue where the Firefly id wouldn't get stored for transactions with a conversion. This means the will display as not pushed in the importer even though they're created in Firefly. If you run the sync command again, a warning will appear in the logging saying `Duplicate of transaction x`. 
I should look into how Firefly decided whether or not a transaction is a duplicate. If no false positives can occur i can probably just update the transaction with the id of the duplicate.

Can you update the application to the latest version (0.2.5, the version is also displayed in the web overview) and see if it resolved your issue? 

Thanks!

**Comment by PhalanxHead** [comment] 2022-08-14 13:20
Hi @robvankeilegom.

Have also just tried the new version, having been getting the same issue in 0.2.4, but unfortunately it still seems to be occurring for me in 0.2.5.

I'd post logs from the `storage/logs` folder, but it doesn't seem to be outputting anything there.

For me, with a fresh install of Firefly3, the Paypal importer now finds ~490 records from paypal, but it doesn't push any to the Firefly 3 instance before this error occurs.

Thanks!

**Comment by robvankeilegom** [comment] 2022-08-19 05:42
@Crumar @PhalanxHead Originally i assumed all transactions not in EUR have a conversion transaction from another currency. That was pretty short sighted of me obviously. I created version 0.2.6 where you can pass an extra `CURRENCY` env. The currency should be a code and should match your currency in Firefly and the PayPal currency (https://developer.paypal.com/api/rest/reference/currency-codes/). @PhalanxHead  I'm guessing that for you, it would be `AUD`.

I don't really have a way of testing other currencies, so let me know how it goes!

**Comment by PhalanxHead** [comment] 2022-08-21 11:18
Heya @robvankeilegom, it's worked like a charm for me mate!
Thanks heaps!!

Now to figure out how to link expenses to my other account :')

**Closed as completed** 2022-08-27 08:28 UTC

**Comment by robvankeilegom** [comment] 2022-08-27 08:29
@PhalanxHead Great! To link the expenses and change them to transfers i personally use a rule under Automation > Rules.
